// src/pages/content/App.vue
<script setup></script>

<template>
    <button @click="test" class="extension btn">
        Extension Content Scripts
    </button>
</template>

<script>
import Ex from '@/extension'

export default {
    data() {
        return {
            data: null,
        }
    },
    mounted() {
        console.log('content scripts')
    },
    methods: {
        test() {
            Ex.sendMsg(
                { channel: 'test', data: 'hello from content scripts' },
                (msg) => {
                    console.log('msg:', msg)
                    alert(msg)
                }
            )
        },
    },
}
</script>
<style>
.extension {
    border: 1px solid red;
}
</style>

// src/pages/content/App.svelte
<script>
    import { onMount } from 'svelte'
    import Counter from '@/components/Counter.svelte'

    import Ex from '@/extension'

    onMount(() => {
        console.log('content scripts')
    })

    function test() {
        Ex.sendMsg(
            { channel: 'test', data: 'hello from content scripts' },
            (msg) => {
                console.log('msg:', msg)
                alert(msg)
            }
        )
    }
</script>

<button on:click={test} class="extension btn">Extension Content</button>
<Counter />

<style>
    .extension {
        border: 1px solid red;
    }
</style>
